spring:
  application:
    name: greeting-service
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /management
  endpoint:
    health:
      show-details: ALWAYS
  info:
    git:
      mode: full

eureka:
  instance:
    appname: ${spring.application.name}
    instanceId: ${spring.application.name}:${server.port}:${spring.application.instance-id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.endpoints.web.base-path}/info
    health-check-url-path: ${management.endpoints.web.base-path}/health
    metadata-map:
      startup: ${random.int}
      zone: primary # This is needed for the load balancer
      profile: ${spring.profiles.active}
      version: #project.version#
      git-version: ${git.commit.id.describe:}
      git-commit: ${git.commit.id.abbrev:}
      git-branch: ${git.branch:}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
    register-with-eureka: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10

springdoc:
  swagger-ui:
    path: /swagger

altimetrik:
  jwt:
    secret: ThisValueWillComeFromSpringConfigServerWhichInTurnWouldFetchItFromGitRepo
    validityInSeconds: 600

logging:
  level:
    ROOT: info
    com.altimetrik.greetingservice: debug